ALTER TABLE COMMUNITY_BOARD DROP CONSTRAINT COMMUNITY_BOARD_CB_WID_FK;

ALTER TABLE COMMUNITY_BOARD
	ADD CONSTRAINT COMMUNITY_BOARD_DELETE
	FOREIGN KEY (CB_WID)
	REFERENCES ACCOUNT(AC_ID)
	ON DELETE CASCADE;
	
	
ALTER TABLE COMMUNITY_BOARD_STATICS DROP CONSTRAINT COMMUNITY_BOARD_STATICS_CBS_WID_FK;

ALTER TABLE COMMUNITY_BOARD_STATICS
	ADD CONSTRAINT COMMUNITY_BOARD_STATICS_DELETE
	FOREIGN KEY (CBS_WID)
	REFERENCES ACCOUNT(AC_ID)
	ON DELETE CASCADE;


ALTER TABLE STUDY_BOARD DROP CONSTRAINT SB_WID_FK;

ALTER TABLE STUDY_BOARD
	ADD CONSTRAINT STUDY_BOARD_DELETE
	FOREIGN KEY (SB_WID)
	REFERENCES ACCOUNT(AC_ID)
	ON DELETE CASCADE;
	

ALTER TABLE COMMUNITY_COMMENT DROP CONSTRAINT COMMUNITY_COMMENT_CC_WID_FK;

ALTER TABLE COMMUNITY_COMMENT
	ADD CONSTRAINT COMMUNITY_COMMENT_DELETE
	FOREIGN KEY (CC_WID)
	REFERENCES ACCOUNT(AC_ID)
	ON DELETE CASCADE;
	

ALTER TABLE COMMUNITY_COMMENT_STATICS DROP CONSTRAINT COMMUNITY_COMMENT_STATICS_CCS_WID_FK;

ALTER TABLE COMMUNITY_COMMENT_STATICS
	ADD CONSTRAINT COMMUNITY_COMMENT_STATICS_DELETE
	FOREIGN KEY (CCS_WID)
	REFERENCES ACCOUNT(AC_ID)
	ON DELETE CASCADE;
	
	
ALTER TABLE STUDY_COMMENT DROP CONSTRAINT SC_WID_FK;

ALTER TABLE STUDY_COMMENT
	ADD CONSTRAINT STUDY_COMMENT_DELETE
	FOREIGN KEY (SC_WID)
	REFERENCES ACCOUNT(AC_ID)
	ON DELETE CASCADE;
	
	
ALTER TABLE LESSON DROP CONSTRAINT LESSON_L_WID_FK;

ALTER TABLE LESSON
	ADD CONSTRAINT LESSON_DELETE
	FOREIGN KEY (L_WID)
	REFERENCES ACCOUNT(AC_ID)
	ON DELETE CASCADE;
	

ALTER TABLE WISHLIST DROP CONSTRAINT WISHLIST_W_ACID_FK;

ALTER TABLE WISHLIST
	ADD CONSTRAINT WISHLIST_DELETE
	FOREIGN KEY (W_ACID)
	REFERENCES ACCOUNT(AC_ID)
	ON DELETE CASCADE;
	
-- payment db 수정
ALTER TABLE PAYMENT DROP CONSTRAINT  "PAYMENT_P_ACID_FK";

ALTER TABLE PAYMENT ADD CONSTRAINT PAYMENT_P_ACID_FK FOREIGN KEY (P_ACID) REFERENCES ACCOUNT(AC_ID)
ON DELETE CASCADE;
	

--22.09.26 추가
ALTER TABLE COMMUNITY_BOARD_STATICS DROP CONSTRAINT COMMUNITY_BOARD_STATICS_CBS_WID_FK;

ALTER TABLE LESSON_MANAGER
	ADD CONSTRAINT LESSON_MANAGER_DELETE
	FOREIGN KEY (LM_WID)
	REFERENCES ACCOUNT(AC_ID)
	ON DELETE CASCADE;